var icons = [
    "fas fa-map-marker-alt", 
    "fas fa-map-marked-alt", 
    "fas fa-map-pin",
    "fas fa-location-arrow",
    "fas fa-globe-europe",
    "fas fa-globe",
    "fas fa-broadcast-tower",
    "fas fa-play",
    "far fa-play-circle",
    "fab fa-pagelines",
    "far fa-star",
    "fas fa-plane",
    "fas fa-certificate",
    "fas fa-camera",
    "fas fa-bullhorn",
    "fas fa-layer-group",
    "fas fa-file-download",
    "fas fa-cloud-download-alt",
    "fas fa-arrow-circle-down",
    "fas fa-eye",
    "fab fa-bluetooth",
    "fas fa-exclamation-triangle",
    "fas fa-wifi",
    "fas fa-phone-square",
    "fas fa-comment-slash",
    "fas fa-street-view",
    "fas fa-battery-three-quarters",
    "fas fa-wrench",
    "fas fa-users",
    "far fa-calendar-check",
    "fas fa-user-tie",
    "fas fa-ellipsis-h",
    "fas fa-business-time",
    "fab fa-usb",
    "fas fa-volume-mute",
    "fas fa-toolbox",
    "far fa-bell-slash",
    "fas fa-user-secret",
    "fas fa-plug",
    "fas fa-check"
]

module.exports = icons;